{{- if and (eq .Values.store.backend "filesystem") .Values.store.filesystem.persistence.enabled (not .Values.store.filesystem.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jenrepo.fullname" . }}-data
  labels:
    {{- include "jenrepo.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.store.filesystem.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.store.filesystem.persistence.size }}
  {{- with .Values.store.filesystem.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
