{{- if and (not .Values.secrets.existingSecret) (or .Values.secrets.s3AccessKeyId .Values.secrets.s3SecretAccessKey .Values.secrets.azureConnectionString .Values.secrets.githubClientSecret .Values.secrets.oidcClientSecret .Values.secrets.licenseKey .Values.secrets.extra) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenrepo.fullname" . }}
  labels:
    {{- include "jenrepo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.s3AccessKeyId }}
  JENREPO_S3_ACCESS_KEY_ID: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.s3SecretAccessKey }}
  JENREPO_S3_SECRET_ACCESS_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.azureConnectionString }}
  JENREPO_AZURE_BLOB_CONNECTION_STRING: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.githubClientSecret }}
  JENREPO_UI_GITHUB_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.oidcClientSecret }}
  JENREPO_UI_OIDC_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.licenseKey }}
  JENREPO_LICENSE_KEY: {{ . | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.extra }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
