{{- if and (not .Values.secrets.existingSecret) (or .Values.secrets.s3AccessKeyId .Values.secrets.s3SecretAccessKey .Values.secrets.gcsAccessKeyId .Values.secrets.gcsSecretAccessKey .Values.secrets.azureConnectionString .Values.secrets.githubClientSecret .Values.secrets.oidcClientSecret .Values.secrets.extra) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenreg.fullname" . }}
  labels:
    {{- include "jenreg.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.s3AccessKeyId }}
  JENREG_S3_ACCESS_KEY_ID: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.s3SecretAccessKey }}
  JENREG_S3_SECRET_ACCESS_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.gcsAccessKeyId }}
  JENREG_GCS_ACCESS_KEY_ID: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.gcsSecretAccessKey }}
  JENREG_GCS_SECRET_ACCESS_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.azureConnectionString }}
  JENREG_AZURE_BLOB_CONNECTION_STRING: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.githubClientSecret }}
  JENREG_UI_GITHUB_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.oidcClientSecret }}
  JENREG_UI_OIDC_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.extra }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
